# Generated by Django 5.1.3 on 2024-11-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Preference",
        ),
        migrations.AlterField(
            model_name="user",
            name="preferences",
            field=models.ManyToManyField(related_name="users", to="video.category"),
        ),
    ]
